# Generated by Django 5.1.2 on 2024-11-01 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=100)),
                ('create', models.BooleanField()),
                ('read', models.BooleanField()),
                ('update', models.BooleanField()),
                ('delete', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterFleetLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=63)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter_store.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=30)),
                ('zone_name', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_project_id', models.CharField(max_length=30)),
                ('fleet_project_id', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('node_count', models.IntegerField()),
                ('cluster_ipv4_cidr', models.CharField(max_length=18)),
                ('services_ipv4_cidr', models.CharField(max_length=18)),
                ('external_load_balancer_ipv4_address_pools', models.CharField(max_length=18)),
                ('sync_repo', models.CharField(max_length=128)),
                ('sync_branch', models.CharField(max_length=50)),
                ('sync_dir', models.CharField(max_length=50)),
                ('secrets_project_id', models.CharField(max_length=30)),
                ('git_token_secrets_manager_name', models.CharField(max_length=255)),
                ('cluster_version', models.CharField(max_length=30)),
                ('maintenance_window_start', models.TimeField(blank=True, null=True)),
                ('maintenance_window_end', models.CharField(blank=True, max_length=30, null=True)),
                ('maintenance_window_recurrence', models.CharField(blank=True, max_length=128, null=True)),
                ('subnet_vlans', models.CharField(max_length=128)),
                ('recreate_on_delete', models.BooleanField(default=False)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter_store.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=100)),
                ('create', models.BooleanField()),
                ('read', models.BooleanField()),
                ('update', models.BooleanField()),
                ('delete', models.BooleanField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter_store.cluster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cluster',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter_store.group'),
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=100)),
                ('create', models.BooleanField()),
                ('read', models.BooleanField()),
                ('update', models.BooleanField()),
                ('delete', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter_store.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter_store.cluster')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter_store.tag')),
            ],
        ),
    ]
