# Generated by Django 5.1.2 on 2024-11-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='tags',
            field=models.ManyToManyField(related_name='clusters', through='parameter_store.ClusterTag', to='parameter_store.tag'),
        ),
        migrations.AlterField(
            model_name='clusterintent',
            name='maintenance_window_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clusterintent',
            name='node_count',
            field=models.IntegerField(default=3),
        ),
    ]
