# Generated by Django 5.1.2 on 2024-11-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter_store', '0002_cluster_data_cluster_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusterrole',
            name='cluster',
        ),
        migrations.DeleteModel(
            name='GlobalRole',
        ),
        migrations.RemoveField(
            model_name='grouprole',
            name='group',
        ),
        migrations.DeleteModel(
            name='ClusterRole',
        ),
        migrations.DeleteModel(
            name='GroupRole',
        ),
    ]
