# Generated by Django 5.1.2 on 2024-11-05 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter_store', '0003_remove_clusterrole_cluster_delete_globalrole_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clusterintent',
            options={'verbose_name': 'Cluster Intent Data', 'verbose_name_plural': 'Cluster Intent Data'},
        ),
        migrations.AlterField(
            model_name='clusterintent',
            name='cluster',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parameter_store.cluster'),
        ),
    ]
