# Generated by Django 5.1.2 on 2024-11-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter_store', '0005_alter_cluster_group_alter_cluster_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clusterfleetlabel',
            options={'verbose_name': 'Cluster Fleet Label', 'verbose_name_plural': 'Cluster Fleet Labels'},
        ),
        migrations.AlterModelOptions(
            name='clustertag',
            options={'verbose_name': 'Cluster Tag', 'verbose_name_plural': 'Cluster Tags'},
        ),
        migrations.RenameField(
            model_name='clusterfleetlabel',
            old_name='label',
            new_name='key',
        ),
        migrations.AddField(
            model_name='clusterfleetlabel',
            name='value',
            field=models.CharField(default=None, max_length=63),
            preserve_default=False,
        ),
    ]
