# Generated by Django 5.1.2 on 2024-11-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter_store', '0006_alter_clusterfleetlabel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterfleetlabel',
            name='key',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
