# Generated by Django 5.1.2 on 2024-11-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter_store', '0007_alter_clusterfleetlabel_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterfleetlabel',
            name='key',
            field=models.CharField(max_length=63),
        ),
        migrations.AddConstraint(
            model_name='clusterfleetlabel',
            constraint=models.UniqueConstraint(fields=('cluster', 'key'), name='unique_cluster_key'),
        ),
    ]
