# Generated by Django 5.1.2 on 2024-11-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter_store', '0008_alter_clusterfleetlabel_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clusterintent',
            old_name='git_token_secrets_manager_name',
            new_name='git_token_secret_manager_name',
        ),
        migrations.AlterField(
            model_name='clusterintent',
            name='cluster_ipv4_cidr',
            field=models.CharField(max_length=18, verbose_name='Cluster IPv4 CIDR'),
        ),
        migrations.AlterField(
            model_name='clusterintent',
            name='cluster_version',
            field=models.CharField(help_text='This is the GDCC control plane version, i.e. "1.7.1"', max_length=30),
        ),
        migrations.AlterField(
            model_name='clusterintent',
            name='external_load_balancer_ipv4_address_pools',
            field=models.CharField(max_length=18, verbose_name='External Load Balancer IPv4 Address Pools'),
        ),
        migrations.AlterField(
            model_name='clusterintent',
            name='fleet_project_id',
            field=models.CharField(max_length=30, verbose_name='Fleet Project ID'),
        ),
        migrations.AlterField(
            model_name='clusterintent',
            name='machine_project_id',
            field=models.CharField(max_length=30, verbose_name='Machine Project ID'),
        ),
        migrations.AlterField(
            model_name='clusterintent',
            name='services_ipv4_cidr',
            field=models.CharField(max_length=18, verbose_name='Services IPv4 CIDR'),
        ),
        migrations.AlterField(
            model_name='clusterintent',
            name='subnet_vlans',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='clusterintent',
            name='sync_branch',
            field=models.CharField(default='main', help_text='For; example: "main" or "master"', max_length=50),
        ),
        migrations.AlterField(
            model_name='clusterintent',
            name='sync_dir',
            field=models.CharField(default='hydrated/clusters/None', max_length=50),
        ),
        migrations.AlterField(
            model_name='clusterintent',
            name='sync_repo',
            field=models.CharField(help_text='This is the full URL to a Git repository', max_length=128),
        ),
        migrations.AlterField(
            model_name='clusterintent',
            name='zone_id',
            field=models.CharField(max_length=30, verbose_name='Zone ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='tag name'),
        ),
    ]
