# Generated by Django 5.1.4 on 2025-01-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAPIPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_get_params_api', 'Can get from params API endpoints')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
