environment         = "staging"
store_id            = "dryrun2-cam-8cc"
project_id          = "daniel-test-proj-411311"
region              = "us-central1"
eps_db_name         = "cloud-sql--daniel-2"
project_id_secrets  = ""