name: Linter and Code Formatting
on:
  pull_request:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: 'true'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install app dependencies
        run: uv sync --frozen --no-install-project --verbose

      - name: Ruff formatting check
        run: uv run ruff format --check .

      - name: Ruff linting check
        run: uv run ruff check .
