on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - terraform/**

name: test dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker build
        run: docker build -t eps .
      - name: invoke built image
        run: docker run -i eps:latest python3 manage.py check
